### ISSUE TITLE
Add tests to compare the Julia and Python model outputs

### ISSUE THREAD

**Issue by FrankErrickson** [FrankErrickson/MimiFAIRv2.jl#6]
Tests against the Python version of FAIR (https://github.com/njleach/FAIR/tree/47c6eec031d2edcf09424394dbb86581a1b246ba)  should be done with data in the `python_replication_data` folder -- original testing created comparison plot and compared Temperature to very low significant digits -- the files uploaded to that folder should be changed so we can continue to reproduce those tests and graphs.

**Comment by lrennels** [comment]
handling this #21  and #20

**Comment by lrennels** [comment]
Done, see additional testing and replication files.
